### ISSUE TITLE
Custom underlines

### ISSUE THREAD

**Issue by brendon-avalos** [Manhattan-Hydraulics/manhattan-hydraulics.github.io#16]
<img width="333" alt="Screen Shot 2021-03-03 at 3 23 04 PM" src="https://user-images.githubusercontent.com/57079598/109867382-6afc5f00-7c34-11eb-87c7-9ce8aa920695.png">

Instead of using out the box underlines should we use a custom one like this one. 

<img width="160" alt="Screen Shot 2021-03-03 at 3 26 12 PM" src="https://user-images.githubusercontent.com/57079598/109867674-cf1f2300-7c34-11eb-9388-babd50584475.png">

**Comment by devinhalladay** [comment]
Fixed in #18
