### ISSUE TITLE
Footer transition

### ISSUE THREAD

**Issue by brendon-avalos** [Manhattan-Hydraulics/manhattan-hydraulics.github.io#17]
I know this is a pain but I think we need to think about how we build the footer again or figure out some solution to have it fade in at the same rate as the background color.

Right now I can see where the footer fades in when I hover over the sections.

**Comment by brendon-avalos** [comment]
<img width="701" alt="Screen Shot 2021-03-03 at 3 28 38 PM" src="https://user-images.githubusercontent.com/57079598/109868007-26bd8e80-7c35-11eb-9a46-3dc72d760326.png">

**Comment by devinhalladay** [comment]
Fixed in #18
