### ISSUE TITLE
Weird bug on load when i my mouse is by the footer

### ISSUE THREAD

**Issue by brendon-avalos** [Manhattan-Hydraulics/manhattan-hydraulics.github.io#19]
<img width="1655" alt="Screen Shot 2021-03-05 at 8 10 17 PM" src="https://user-images.githubusercontent.com/57079598/110189914-dd18a380-7dee-11eb-95bf-950a9bb56f7d.png">

:o

**Comment by brendon-avalos** [comment]
<img width="1655" alt="Screen Shot 2021-03-05 at 8 11 24 PM" src="https://user-images.githubusercontent.com/57079598/110189951-fcafcc00-7dee-11eb-8c67-cab33433ece1.png">

**Comment by devinhalladay** [comment]
This has been fixed! Thx for point out Brendo 💋
