### ISSUE TITLE
Make panels active/stay active/triggered on focus. 

### ISSUE THREAD

**Issue by samWinfield** [Manhattan-Hydraulics/manhattan-hydraulics.github.io#20]
User should be able to use focus (tab key) to trigger the left and right panels. When the focus is on the element, user should be able to tab into the section, through all of the links, and into the other section, then to the footer.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/19784290/142487173-5a99743d-b6b8-46f7-84f9-729463268961.png">
<img width="985" alt="image" src="https://user-images.githubusercontent.com/19784290/142487203-5727c797-c31d-4537-95ef-cbae2c893c1f.png">

**Comment by devinhalladay** [comment]
I am going to close this for now without addressing. I agree our site should be more accessible but I don't know if we will have a new website a month or two from now, and I don't think it's worth doing if we need to redesign it anyway.

If we decide to keep the current site once portfolio work is underway, I will reopen this and address it.
