### ISSUE TITLE
Final QA Pass

### ISSUE THREAD

**Issue by devinhalladay** [Manhattan-Hydraulics/manhattan-hydraulics.github.io#8]
I need some things from each of you BY EOD MONDAY LATEST.

### @timcasasola
- [ ] Final pass over the site's copy, as well as the copy displayed in share cards and search engines. 
  - You can view the SEO text by Googling us. The copy is different from the copywriting on-site, which I think is actually a good thing (more focused on hitting searches for "product design" than "product studio")
  - You can view share card by going to [Twitter Card Validator](https://cards-dev.twitter.com/validator) and entering our URL.

### @brendonsanctuary + @simonenr 
- [ ] Check share card image at [Twitter Card Validator](https://cards-dev.twitter.com/validator). 
  - I chose the white version because it stood out more, and had to alter the proportions of the nameplate and logotype to work better in its real context (eg. on twitter)
- [x] Do a final pass on visual design of the site, on desktop and mobile
  - I diverged from the designs in a couple places, namely spacing and type styles, to improve readability and UX (eg. a link should look like a link; using sentence-case for the headers felt weird because Whyte weights are not visually different enough.)

### @hhff 
- [x] Lmk if you have any idea why I can't get Google to index our site.
  -  I tried a million times in the search console. Maybe this will be better once we have folks sharing our URL. There are also some semantics issues I'm aware of (eg. we have two `<main/>` elements) but I doubt those would cause indexing to fail (and I don't have much appetite to fix them unless it's really necessary)

### Everyone
- Please interact with the site. Click links, play with the hover effects, resize your browser a few times, try it on your phone, preferred browser, etc. Note any issues here.

**Comment by devinhalladay** [comment]
Update on SEO:

After doing some research, it seems like Google is **refusing** to index our site because it has so little content. I can't imagine that's permanent, because lots of sites with little content must be in Google's index, but for now there's really not much to be done.

That said, I think Google's crawlers will be more "enticed" to index our page when people are linking to it, so maybe next week we will see a change after launch.

EDIT 03/01/20: We finally got indexed!!! 
![image](https://user-images.githubusercontent.com/1934813/109519746-866f3a80-7a79-11eb-9dd9-cd1a6f28943d.png)

**Comment by brendonsanctuary** [comment]
Hover reveal still feels a bit buggy. Also content doesnt always show up.
<img width="2015" alt="Screen Shot 2021-03-01 at 12 17 17 PM" src="https://user-images.githubusercontent.com/58054507/109533575-6135f880-7a88-11eb-9ffe-0e46a83e764e.png">

**Comment by simonenr** [comment]
The site is looking so so great — thank you for all your hard work on it. Here are a few fixes I’m seeing: 

- Close the tracking of the type slightly (it’s -2% tracking in Figma, except for the caps typesetting, which I think we killed anyway) 
- Close the space between the headline and the sub copy about 25% 
- Use dashes instead of bullets for the UL 
- Use sentence-case instead of all-caps for the bulleted list headlines 
- It looks like we’re dimming the sub-copy (that rests on the gradient) on hover. Is this for any specific reason? 
- “We pride ourselves on being kind, collaborative, technically skilled, and adaptive to change” should be a part of the paragraph above as far as I can tell, and shouldn’t be bolded 
- “We work with clients to:” shouldn’t be bolded 
- Drop to 16pt, instead of 18pt, on the small breakpoint 
- Have we purchased the real web fonts now instead of the trial?

**Comment by devinhalladay** [comment]
> Hover reveal still feels a bit buggy. Also content doesnt always show up.
> <img alt="Screen Shot 2021-03-01 at 12 17 17 PM" width="2000" src="https://user-images.githubusercontent.com/58054507/109533575-6135f880-7a88-11eb-9ffe-0e46a83e764e.png">

There's a weird bug where the content sometimes disappears if you hover one panel before the other panel finishes its animation. I'll look into a fix this eve

Good to know I'm not the only one with the issue

**Comment by winnieyoe** [comment]
Looking great!! 
- On Firefox, the scrollbar in the middle shows up (#9)
![hydro](https://user-images.githubusercontent.com/5560263/109535212-4c5a6480-7a8a-11eb-8b64-ee6e9f78f3be.PNG)
- On mobile the underline does not show up as dashed lines (maybe because on mobile I am on safari?)

**Comment by devinhalladay** [comment]
> * Have we purchased the real web fonts now instead of the trial?

@simonenr nope we have not. Would you please purchase a license (we can just buy all the weights, I think) using the Big Card in the Garden3D 1Password? Send a receipt to Hugh

**Comment by brendonsanctuary** [comment]
**Content width**

_Looks nice at 1280px_
![image](https://user-images.githubusercontent.com/58054507/109535647-cc80ca00-7a8a-11eb-8cf3-7cace114654f.png)


_Looks a lil too wild at larger scales_ 
<img width="2134" alt="Screen Shot 2021-03-01 at 12 32 35 PM" src="https://user-images.githubusercontent.com/58054507/109535697-db677c80-7a8a-11eb-82cc-97aa2dd48462.png">


**Possible solution:**
Max width at content level of around 600px for both sides.

**Comment by devinhalladay** [comment]
Closing this — QA now being tracked [here](https://docs.google.com/spreadsheets/d/1ACRGjE7MRoUirlGMKxNsJJIWroCTxT_buxLtAX2Ekx4/edit?usp=sharing)
