### ISSUE TITLE
Firefox Scrollbars

### ISSUE THREAD

**Issue by winnieyoe** [Manhattan-Hydraulics/manhattan-hydraulics.github.io#9]
On Firefox, scroll bars show up in the middle of the page
![hydro](https://user-images.githubusercontent.com/5560263/109531588-1915d680-7a86-11eb-9ea1-7da57e306ed1.PNG)

**Comment by devinhalladay** [comment]
@winnieyoe does this need a fix?

**Comment by devinhalladay** [comment]
Fixed by ce7939e
